//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGVIEN
    {
        public string MaPV { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public string DienThoai { get; set; }
        public System.DateTime NgayVaoLam { get; set; }
        public int MaLoaiPV { get; set; }
        public decimal Luong { get; set; }
    
        public virtual LoaiPhongVien LoaiPhongVien { get; set; }
    }
}
